### PR TITLE
Update class to match output of UVic ones

### PR DESCRIPTION
**Pull request by gpoo**
According to files obtained on December 28, 2014 from
http://www.uvic.ca/library/featured/collections/uvic/thesis/latex/latextemplates.php

### CODE REVIEW

**Comment by rchurchley** [comment]
Although the horizontal rules above committee members are in the current UVic LaTeX template, do you know if they are actually required by library style? None of [the most recently accepted theses on UVicSpace](https://dspace.library.uvic.ca:8443/handle/1828/12) include them.

**Comment by gpoo** [comment]
I think the ones written in LaTeX, yes. For example:

https://dspace.library.uvic.ca:8443/handle/1828/5827
https://dspace.library.uvic.ca:8443/handle/1828/6490
https://dspace.library.uvic.ca:8443/handle/1828/5837

All of them from this year. I took a random sample, guessing by the title name whether is a field related to Science (more prone to use LaTeX, and therefore the templates provided by the library).

I don't know whether is a requirement by the library, though.

**Comment by gpoo** [comment]
Probably the rule is **not** a requirement, as the MS Word template does not have it, and the use of templates is voluntary.  However, this "requirement" might vary from department to department, or from faculty to faculty. For example, a faculty chiming because the format of a thesis/dissertation looks different of what it is used to see.

**Comment by rchurchley** [comment]
> Probably the rule is not a requirement, as the MS Word template does not have it, and the use of templates is voluntary.

If the MS Word template does not have it, then it could have been a requirement long ago. I agree that it seems it is not a requirement anymore. The question is, should we include the horizontal rules by default?

**Pro**
Ensures consistency with older theses in the same department.

**Con**
Reduces consistency with theses from other departments.
Adds more code.
Non-trivial to remove if not wanted.

I lean towards leaving out the horizontal rule for simplicity's sake. If we leave it out and your supervisor wants it in, you can easily add it without changing the class file (either manually add it to your `\member` declarations or using the `\pretocmd` macro from the `etoolbox` package). But if we decided to include it by default and your supervisor _didn't_ want it, it would be more difficult to remove it.

**Comment by rchurchley** [comment]
The other part of your pull request looks fine. If you've had better experience with those values for `\cftfignumwidth` and `\floatpagefraction`, I would be happy to merge those lines in. Thanks for the tweaks!

**Comment by gpoo** [comment]
I just realized that those are nitpicks. No need to merge them, as I can apply them directly in my own class.

I have some long captions, and the listing looks a bit odd to my eyes in comparison with the listing of tables. I even wonder, why do they have to be that different.

Similar thing with the floating images. When having side-by-side floating elements (subfloat), I can make them wider without getting them jumping to the next page or the end of the section. Just nitpick.

**Comment by rchurchley** [comment]
Righto. Thanks for bringing these issues up, and please let me know (via GitHub Issue or pull request) if you have any more suggestions! Nitpicks are fine as long as everybody benefits from them :)

**Pull request closed without merging**
